# PostgreSQL. Versions 8.2 and up are supported.
#

default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_UN"] %>
  template: <%= ENV.fetch("DB_TEMPLATE") { 'template0' } %>

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost
  #port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # The server defaults to notice.
  #min_messages: warning

  # The specified database role being used to connect to postgres.
  # To create additional roles in postgres see `$ createuser --help`.
  # When left blank, postgres will use the default role. This is
  # the same name as the operating system user that initialized the database.
  #username: myapp

  # The password associated with the postgres role (username).
  #password:

development:
  <<: *default
  database: visitor_development
  password: <%= Rails.application.secrets[:db_pwd] %>

test:
  <<: *default
  database: visitor_test
  password: <%= Rails.application.secrets[:db_pwd] %>

production:
  <<: *default
  database: visitor_production
  password: <%= Rails.application.secrets[:db_pwd] %>

