# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: Demo User
  admin_email: user@demo.com
  admin_password: changeme
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  domain_name: example.com
  db_pwd: <%= ENV["DB_PW"] %>
  secret_key_base: 2a7cc5ed6cc8067a43ca9645cd344e9db1e295d8885fffba3d06268b5098210843f21f8a964736de26b3be1b61171d02b3a751a91372b46fcbb2cdc207d99c1d

test:
  domain_name: example.com 
  db_pwd: <%= ENV["DB_PW"] %>
  secret_key_base: 0d70ee8375655c866f6f239e530f560dfbd30b9e2cbfa1bc5ec3b5a3ab04ffdab841f3574e2b8cab1d9a109c3eebdacc593edea83922992347274d026df3afa3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: Demo User
  admin_email: user@demo.com
  admin_password: changeme
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %> 
  domain_name: <%= ENV.fetch("DOMAIN_NAME") { 'serene-spire-81765.herokuapp.com' } %>
  db_pwd: <%= ENV["DB_PW"] %>
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") { '8af4328bf41aeb8f0f3db65dadec42cfa867d8f5501b17eb864fb6cd39d624744c5a6bcf89fa85cf09714ec85d47f83436fad5455db416d567494b35963aa76f' } %>

